// Evolve module — Micro-tools, Swarm, Compaction, Scratchpad
// Ported from: zara-evolve, zara-swarm, zara-compaction, zara-scratchpad

import fs from 'fs';
import path from 'path';
import { tool } from '@opencode-ai/plugin';
import { FileStore, HOME, estimateTokens, ensure, loadJson, saveJson, contextPressure as sharedPressure } from '../infra/store.mjs';
import { spawnBackground, backgroundStatus, collectBackground, pendingCount } from './background.mjs';

const z = tool.schema;

// ─── Constants ──────────────────────────────────────────────────────────────

const EVOLVE_DIR = path.join(HOME, 'evolve');
const MICRO_TOOLS_FILE = path.join(EVOLVE_DIR, 'micro-tools.json');
const PROMPT_SCORES_FILE = path.join(EVOLVE_DIR, 'prompt-scores.json');
const RULES_FILE = path.join(EVOLVE_DIR, 'workflow-rules.json');
const AUTO_CRYSTAL_LOG = path.join(EVOLVE_DIR, 'auto-crystallized.json');

const COMPACT_DIR = path.join(HOME, 'compaction');
const CONTEXT_WINDOW = 200000;
const PRESSURE_WARN = 0.70;
const PRESSURE_COMPACT = 0.85;

const SCRATCH_DIR = path.join(HOME, 'scratch');

// ─── Helpers ─────────────────────────────────────────────────────────────────

function uid(prefix = 'sw') {
  return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 6)}`;
}

// ─── Scratchpad Cache ───────────────────────────────────────────────────────

let _scratchCache = null;
let _scratchMtime = 0;
let _scratchFilePath = null;

function scratchFile(directory) {
  const hash = Buffer.from(directory || process.cwd()).toString('base64url').slice(0, 16);
  return path.join(SCRATCH_DIR, `${hash}.json`);
}

function loadScratch(file) {
  try {
    if (file === _scratchFilePath) {
      const stat = fs.statSync(file);
      if (_scratchCache && stat.mtimeMs === _scratchMtime) return _scratchCache;
    }
    const data = JSON.parse(fs.readFileSync(file, 'utf-8'));
    if (file === _scratchFilePath) { _scratchCache = data; try { _scratchMtime = fs.statSync(file).mtimeMs; } catch {} }
    return data;
  } catch { return { notes: [], plan: null }; }
}

function saveScratch(file, data) {
  ensure(SCRATCH_DIR);
  data.updatedAt = new Date().toISOString();
  fs.writeFileSync(file, JSON.stringify(data, null, 2), 'utf-8');
  if (file === _scratchFilePath) { _scratchCache = data; try { _scratchMtime = fs.statSync(file).mtimeMs; } catch {} }
}

// ─── Auto-Crystallize ──────────────────────────────────────────────────────

function autoCrystallize() {
  const reflectFile = path.join(HOME, 'reflections', 'patterns.json');
  const patterns = loadJson(reflectFile, []);
  const microTools = loadJson(MICRO_TOOLS_FILE, []);
  const log = loadJson(AUTO_CRYSTAL_LOG, []);

  let created = 0;
  for (const p of patterns) {
    if (p.occurrences >= 3 && !microTools.find(t => t.name === p.name) && !log.includes(p.name)) {
      microTools.push({
        name: p.name,
        trigger: p.context || p.name,
        steps: [p.approach],
        tools: [],
        notes: `Auto-crystallized from ${p.occurrences} reflections`,
        uses: 0,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        autoGenerated: true,
      });
      log.push(p.name);
      created++;
    }
  }

  if (created > 0) {
    saveJson(MICRO_TOOLS_FILE, microTools);
    saveJson(AUTO_CRYSTAL_LOG, log);
  }
  return created;
}

// ─── Module Export ──────────────────────────────────────────────────────────

export default function createEvolve({ client, directory } = {}) {
  let _crystallized = false;
  let _selfImproveNudged = false;
  function ensureCrystallized() {
    if (_crystallized) return;
    _crystallized = true;
    try { autoCrystallize(); } catch {}
  }

  const contextPressure = { estimatedTokens: 0, pressure: 0, lastCheck: null };

  const scratchFilepath = scratchFile(directory || process.cwd());
  _scratchFilePath = scratchFilepath;

  // Mtime-based transform cache
  let _transformCache = { text: null, mtimes: {} };

  return {
    // ── Hooks ──────────────────────────────────────────────────────────────

    inject(messages) {
      // 1. Evolve: micro-tools + rules + prompt adaptations
      const hasAny = [MICRO_TOOLS_FILE, RULES_FILE, PROMPT_SCORES_FILE].some(f => {
        try { fs.accessSync(f); return true; } catch { return false; }
      });

      if (hasAny) {
        try { ensureCrystallized(); } catch {}

        let stale = !_transformCache.text;
        for (const f of [MICRO_TOOLS_FILE, RULES_FILE, PROMPT_SCORES_FILE]) {
          try {
            const mt = fs.statSync(f).mtimeMs;
            if (_transformCache.mtimes[f] !== mt) { stale = true; _transformCache.mtimes[f] = mt; }
          } catch {
            if (_transformCache.mtimes[f]) { stale = true; delete _transformCache.mtimes[f]; }
          }
        }

        if (!stale && _transformCache.text) {
          const last = messages[messages.length - 1];
          if (last && last.role === 'system') {
            last.content += '\n\n' + _transformCache.text;
          } else {
            messages.push({ role: 'system', content: _transformCache.text });
          }
        } else if (stale) {
          const microTools = loadJson(MICRO_TOOLS_FILE, []);
          const rules = loadJson(RULES_FILE, []);
          const promptScores = loadJson(PROMPT_SCORES_FILE, {});
          const parts = [];

          if (microTools.length > 0) {
            const top = [...microTools]
              .sort((a, b) => b.uses - a.uses)
              .slice(0, 3)
              .map(t => `${t.name}(${t.uses}x): ${t.trigger}`);
            parts.push(`[Micro-tools] ${top.join(' | ')}`);
          }

          if (rules.length > 0) {
            const highRules = rules.filter(r => r.priority === 'high');
            if (highRules.length) {
              parts.push(`[Rules] ${highRules.map(r => `"${r.when}" → ${r.then}`).join(' | ')}`);
            }
          }

          const adaptations = [];
          for (const [instruction, scores] of Object.entries(promptScores)) {
            const total = scores.helpful + scores.neutral + scores.harmful;
            if (total < 3) continue;
            const harmRate = scores.harmful / total;
            if (harmRate > 0.5) adaptations.push(`SUPPRESS: "${instruction}"`);
          }
          if (adaptations.length) parts.push(`[Adapt] ${adaptations.join(' | ')}`);

          _transformCache.text = parts.length ? parts.join('\n\n') : null;
          if (_transformCache.text) {
            const last = messages[messages.length - 1];
            if (last && last.role === 'system') {
              last.content += '\n\n' + _transformCache.text;
            } else {
              messages.push({ role: 'system', content: _transformCache.text });
            }
          }
        }
      }

      // 2. Compaction: token pressure estimation
      const totalTokens = messages.reduce((sum, m) => {
        const text = typeof m.content === 'string' ? m.content : JSON.stringify(m.content || '');
        return sum + estimateTokens(text);
      }, 0);
      contextPressure.estimatedTokens = totalTokens;
      contextPressure.pressure = totalTokens / CONTEXT_WINDOW;
      contextPressure.lastCheck = new Date().toISOString();
      sharedPressure.level = contextPressure.pressure;

      if (contextPressure.pressure > PRESSURE_COMPACT) {
        const cutoff = messages.length - 10;
        for (let i = 0; i < cutoff; i++) {
          const msg = messages[i];
          if (msg?.role === 'tool' && typeof msg.content === 'string' && msg.content.length > 300) {
            msg.content = msg.content.slice(0, 150) + '\n...[truncated]';
          }
        }
        const sys2 = messages.find(m => m.role === 'system');
        if (sys2) sys2.content += `\n\n[Context ${Math.round(contextPressure.pressure * 100)}%] CRITICAL. Call zara_compact NOW.`;
      } else if (contextPressure.pressure > PRESSURE_WARN) {
        const sys2 = messages.find(m => m.role === 'system');
        if (sys2) sys2.content += `\n\n[Context ${Math.round(contextPressure.pressure * 100)}%] Consider zara_compact.`;
      }

      // 3. Scratchpad: inject plan only (notes available via tool)
      const data = loadScratch(scratchFilepath);
      if (data.plan) {
        const age = data.updatedAt ? (Date.now() - new Date(data.updatedAt).getTime()) / 3600000 : 999;
        if (age <= 4) {
          const sys3 = messages.find(m => m.role === 'system');
          if (sys3) sys3.content += `\n\n[Plan] ${data.plan.content.slice(0, 150)}`;
        }
      }

      // 4. Self-improvement — nudge once per session only
      if (!_selfImproveNudged) {
        try {
          const pendingFile = path.join(HOME, 'pending-improvements.json');
          if (fs.existsSync(pendingFile)) {
            const pending = loadJson(pendingFile, []);
            const due = pending.filter(p => p.type === 'self-improve' && p.status === 'pending');
            if (due.length > 0) {
              const sys2 = messages.find(m => m.role === 'system');
              if (sys2) sys2.content += `\n\n[Self-Improve] ${due.length} pending. Run zara_self_improve(phase:"full") when idle.`;
              _selfImproveNudged = true;
            }
          }
        } catch {}
      }

      return messages;
    },

    transformMessages(messages) {
      if (!messages || messages.length < 20) return messages;

      const cutoff = messages.length - 10;
      for (let i = 0; i < cutoff; i++) {
        const msg = messages[i];
        if (!msg?.info?.parts) continue;
        for (const part of msg.info.parts) {
          if (part.type === 'tool-invocation' && part.result && part.result.length > 500) {
            part.result = part.result.slice(0, 200) + '\n...[truncated — call tool again if needed]';
          }
        }
      }
      return messages;
    },

    onCompact() {
      // Provide compaction snapshot
      ensure(COMPACT_DIR);
      const files = fs.readdirSync(COMPACT_DIR)
        .filter(f => f.startsWith('compact-') && f.endsWith('.json'))
        .sort()
        .reverse();

      if (files.length) {
        const latest = JSON.parse(fs.readFileSync(path.join(COMPACT_DIR, files[0]), 'utf-8'));
        // Return data for the composition root to use
        return { context: `Last compaction state: ${JSON.stringify(latest)}` };
      }
      return null;
    },

    dispose() {},

    // ── Tools ──────────────────────────────────────────────────────────────

    tools: {
      // ── Evolve Tools ────────────────────────────────────────────────────

      evolve_crystallize: tool({
        description: 'Save repeated pattern as reusable micro-tool.',
        args: {
          name: z.string().describe('Micro-tool name (e.g. "go-test-debug", "pr-review-checklist")'),
          trigger: z.string().describe('When to use this (situation description)'),
          steps: z.array(z.string()).describe('Exact steps to follow'),
          tools: z.array(z.string()).optional().describe('Which tools to call in sequence'),
          notes: z.string().optional().describe('Additional context or caveats'),
        },
        async execute(args) {
          const microTools = loadJson(MICRO_TOOLS_FILE, []);
          const existing = microTools.findIndex(t => t.name === args.name);
          const entry = {
            name: args.name,
            trigger: args.trigger,
            steps: args.steps,
            tools: args.tools || [],
            notes: args.notes || '',
            uses: existing >= 0 ? (microTools[existing].uses || 0) + 1 : 0,
            createdAt: existing >= 0 ? microTools[existing].createdAt : new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          };

          if (existing >= 0) microTools[existing] = entry;
          else microTools.push(entry);

          saveJson(MICRO_TOOLS_FILE, microTools);
          return { output: `Micro-tool crystallized: "${args.name}" (${args.steps.length} steps). Will be suggested when trigger matches.` };
        },
      }),

      evolve_lookup: tool({
        description: 'Find matching micro-tools for current task.',
        args: {
          situation: z.string().describe('Describe what you are about to do'),
        },
        async execute(args) {
          const microTools = loadJson(MICRO_TOOLS_FILE, []);
          if (!microTools.length) return { output: 'No micro-tools yet. Build them via evolve_crystallize after completing repeated tasks.' };

          const terms = args.situation.toLowerCase().split(/\s+/).filter(w => w.length >= 3);
          const matched = microTools.filter(t => {
            const text = `${t.name} ${t.trigger} ${t.steps.join(' ')}`.toLowerCase();
            return terms.filter(term => text.includes(term)).length >= 2;
          });

          if (!matched.length) return { output: 'No matching micro-tools. Proceed manually and crystallize if it becomes a pattern.' };

          const lines = matched.map(t => [
            `### ${t.name} (used ${t.uses}x)`,
            `**When**: ${t.trigger}`,
            `**Steps**: ${t.steps.map((s, i) => `${i + 1}. ${s}`).join('\n')}`,
            t.tools.length ? `**Tools**: ${t.tools.join(', ')}` : '',
            t.notes ? `**Notes**: ${t.notes}` : '',
          ].filter(Boolean).join('\n'));

          return { output: lines.join('\n\n') };
        },
      }),

      evolve_rule: tool({
        description: 'Create workflow rule (when X, do Y).',
        args: {
          when: z.string().describe('Trigger condition (natural language, e.g. "user asks about Go performance")'),
          then: z.string().describe('Action to take (e.g. "load golang-expert skill, check benchmarks first")'),
          priority: z.enum(['high', 'medium', 'low']).optional().describe('Rule priority (default medium)'),
        },
        async execute(args) {
          const rules = loadJson(RULES_FILE, []);
          rules.push({
            when: args.when,
            then: args.then,
            priority: args.priority || 'medium',
            createdAt: new Date().toISOString(),
            fired: 0,
          });
          saveJson(RULES_FILE, rules);
          return { output: `Rule created: WHEN "${args.when}" → THEN "${args.then}"` };
        },
      }),

      evolve_rules: tool({
        description: 'List all workflow rules.',
        args: {},
        async execute() {
          const rules = loadJson(RULES_FILE, []);
          if (!rules.length) return { output: 'No workflow rules defined yet.' };
          const lines = rules.map((r, i) =>
            `${i + 1}. [${r.priority}] WHEN "${r.when}" → THEN "${r.then}" (fired ${r.fired}x)`
          );
          return { output: lines.join('\n') };
        },
      }),

      evolve_check_rules: tool({
        description: 'Check rules matching current situation.',
        args: {
          situation: z.string().describe('Describe current task/context'),
        },
        async execute(args) {
          const rules = loadJson(RULES_FILE, []);
          if (!rules.length) return { output: 'No rules to check.' };

          const terms = args.situation.toLowerCase().split(/\s+/).filter(w => w.length >= 3);
          const matched = rules.filter(r => {
            const text = r.when.toLowerCase();
            return terms.filter(t => text.includes(t)).length >= 2;
          });

          if (!matched.length) return { output: 'No rules match this situation.' };

          for (const m of matched) m.fired++;
          saveJson(RULES_FILE, rules);

          const lines = matched
            .sort((a, b) => ({ high: 3, medium: 2, low: 1 }[b.priority] || 2) - ({ high: 3, medium: 2, low: 1 }[a.priority] || 2))
            .map(r => `- [${r.priority}] **${r.then}** (because: ${r.when})`);
          return { output: `## Matching Rules\n${lines.join('\n')}` };
        },
      }),

      // ── Compaction Tools ────────────────────────────────────────────────

      zara_compact: tool({
        description: 'Compact working state to preserve context.',
        args: {
          activeTasks: z.array(z.string()).describe('Tasks currently in progress'),
          completedTasks: z.array(z.string()).optional().describe('Tasks completed this session'),
          keyDecisions: z.array(z.string()).describe('Important decisions made (preserve these)'),
          activeFiles: z.array(z.string()).optional().describe('Files currently being worked on'),
          openQuestions: z.array(z.string()).optional().describe('Unresolved questions'),
          summary: z.string().describe('Compressed summary of work so far — what matters for continuation'),
        },
        async execute(args) {
          ensure(COMPACT_DIR);
          const snapshot = {
            id: uid('compact'),
            ts: new Date().toISOString(),
            project: directory || process.cwd(),
            ...args,
          };

          const file = path.join(COMPACT_DIR, `${snapshot.id}.json`);
          fs.writeFileSync(file, JSON.stringify(snapshot, null, 2), 'utf-8');

          const files = fs.readdirSync(COMPACT_DIR)
            .filter(f => f.startsWith('compact-') && f.endsWith('.json'))
            .sort()
            .reverse();
          for (const old of files.slice(10)) {
            try { fs.unlinkSync(path.join(COMPACT_DIR, old)); } catch {}
          }

          return {
            output: [
              `Context compacted → ${snapshot.id}`,
              `Active: ${args.activeTasks.join(', ')}`,
              `Decisions preserved: ${args.keyDecisions.length}`,
              '',
              'You can now proceed with reduced context. The summary above is your working state.',
            ].join('\n'),
          };
        },
      }),

      // ── Scratchpad Tools ────────────────────────────────────────────────

      scratch_note: tool({
        description: 'Write scratchpad note.',
        args: {
          content: z.string().describe('The note content'),
          tag: z.enum(['finding', 'hypothesis', 'decision', 'blocker', 'todo', 'learning']).optional().describe('Note category'),
        },
        async execute(args) {
          const data = loadScratch(scratchFilepath);
          data.notes.push({
            content: args.content,
            tag: args.tag || 'finding',
            ts: new Date().toISOString(),
          });
          if (data.notes.length > 50) data.notes = data.notes.slice(-50);
          saveScratch(scratchFilepath, data);
          return { output: `Note saved (${args.tag || 'finding'}). Total: ${data.notes.length}` };
        },
      }),

      scratch_plan: tool({
        description: 'Set current working plan.',
        args: {
          plan: z.string().describe('The current plan (overwrites previous)'),
        },
        async execute(args) {
          const data = loadScratch(scratchFilepath);
          data.plan = { content: args.plan, ts: new Date().toISOString() };
          saveScratch(scratchFilepath, data);
          return { output: 'Plan updated.' };
        },
      }),

      scratch_read: tool({
        description: 'Read scratchpad.',
        args: {
          limit: z.number().optional().describe('Max notes to return (default 10)'),
        },
        async execute(args) {
          const data = loadScratch(scratchFilepath);
          const limit = args.limit || 10;
          const parts = [];

          if (data.plan) {
            parts.push(`## Plan\n${data.plan.content}\n(set: ${data.plan.ts})`);
          }

          const recent = data.notes.slice(-limit);
          if (recent.length) {
            parts.push(`## Notes (${recent.length}/${data.notes.length})`);
            for (const n of recent) {
              parts.push(`- [${n.tag}] ${n.content}`);
            }
          }

          return { output: parts.length ? parts.join('\n\n') : 'Scratchpad is empty.' };
        },
      }),

      // ── Background Agent Tools ──────────────────────────────────────────

      zara_background: tool({
        description: 'Spawn background agent task.',
        args: {
          agent: z.string().describe('Agent to dispatch (e.g., architect, testing-lead)'),
          prompt: z.string().describe('Task prompt for the agent'),
        },
        async execute(args, ctx) {
          if (!client) return { output: 'No client available for background dispatch.' };
          const sessionID = ctx?.sessionID;
          if (!sessionID) return { output: 'No session context for background dispatch.' };
          const result = spawnBackground(client, sessionID, args.agent, args.prompt);
          if (result.error) return { output: `Error: ${result.error}` };
          return { output: `Background task ${result.id} started: @${result.agent} is working on it.` };
        },
      }),

      zara_background_status: tool({
        description: 'Check background task status.',
        args: {
          collect: z.string().optional().describe('Task ID to collect result from (e.g., bg-1)'),
        },
        async execute(args) {
          if (args.collect) {
            const result = collectBackground(args.collect);
            if (result.error) return { output: `Error: ${result.error}` };
            if (result.status === 'still running') return { output: `Task ${args.collect} still running (${Math.round(result.elapsed / 1000)}s elapsed)` };
            return { output: `## Background Result: ${result.agent}\n\n${(result.result || result.error || 'no output').slice(0, 2000)}` };
          }
          const status = backgroundStatus();
          if (!status.length) return { output: 'No background tasks.' };
          const lines = status.map(t => `- ${t.id} (@${t.agent}): ${t.done ? 'done' : `running ${Math.round(t.elapsed / 1000)}s`}${t.error ? ` [error: ${t.error}]` : ''}`);
          return { output: `## Background Tasks (${pendingCount()} pending)\n\n${lines.join('\n')}` };
        },
      }),
    },
  };
}
