#!/usr/bin/env node
// Zara Dashboard — CLI viewer for memory, metrics, and patterns
//
// Usage:
//   node dashboard.mjs              # full overview
//   node dashboard.mjs memory       # memory stats
//   node dashboard.mjs metrics      # metrics
//   node dashboard.mjs patterns     # learned patterns
//   node dashboard.mjs procedures   # saved procedures

import fs from 'fs';
import path from 'path';
import os from 'os';

const HOME = path.join(os.homedir(), '.zara');
const load = (file, fallback) => {
  try { return fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, 'utf-8')) : fallback; }
  catch { return fallback; }
};

const cmd = process.argv[2] || 'all';

function showMemory() {
  const semantic = load(path.join(HOME, 'memory', 'semantic.json'), {});
  const procs = load(path.join(HOME, 'memory', 'procedural.json'), []);
  let episodes = 0;
  try {
    const f = path.join(HOME, 'memory', 'episodic.jsonl');
    if (fs.existsSync(f)) episodes = fs.readFileSync(f, 'utf-8').trim().split('\n').length;
  } catch {}

  console.log('\n📊 MEMORY');
  console.log(`  Episodic:   ${episodes} events`);
  console.log(`  Semantic:   ${Object.keys(semantic).length} facts`);
  console.log(`  Procedural: ${procs.length} workflows`);

  if (Object.keys(semantic).length > 0) {
    console.log('\n  Top semantic:');
    Object.entries(semantic)
      .sort((a, b) => (b[1].reinforced || 1) - (a[1].reinforced || 1))
      .slice(0, 5)
      .forEach(([k, v]) => console.log(`    ${k}: ${v.value} (×${v.reinforced || 1})`));
  }
}

function showMetrics() {
  const dir = path.join(HOME, 'metrics');
  if (!fs.existsSync(dir)) { console.log('\n📈 METRICS: no data yet'); return; }

  const files = fs.readdirSync(dir).filter(f => f.endsWith('.json')).sort().reverse().slice(0, 7);
  console.log('\n📈 METRICS (last 7 days)');
  for (const f of files) {
    const d = load(path.join(dir, f), {});
    const rate = d.toolCalls?.total > 0 ? Math.round((d.toolCalls.success / d.toolCalls.total) * 100) : 0;
    console.log(`  ${f.replace('.json', '')}: ${d.toolCalls?.total || 0} calls, ${rate}% success, ${d.toolCalls?.error || 0} errors`);
  }
}

function showPatterns() {
  const patterns = load(path.join(HOME, 'reflections', 'patterns.json'), []);
  console.log(`\n🧠 PATTERNS (${patterns.length} learned)`);
  if (!patterns.length) { console.log('  None yet.'); return; }
  patterns.sort((a, b) => b.occurrences - a.occurrences).slice(0, 10)
    .forEach(p => console.log(`  ${p.name} (×${p.occurrences}): ${p.approach}`));
}

function showProcedures() {
  const procs = load(path.join(HOME, 'memory', 'procedural.json'), []);
  console.log(`\n\u2699\uFE0F  PROCEDURES (${procs.length} saved)`);
  if (!procs.length) { console.log('  None yet.'); return; }
  procs.slice(0, 10).forEach(p =>
    console.log(`  ${p.name} (used ${p.uses}x, ${Math.round(p.successRate * 100)}% success)\n    ${p.steps.join(' \u2192 ')}`)
  );
}

function showMicroTools() {
  const tools = load(path.join(HOME, 'evolve', 'micro-tools.json'), []);
  console.log(`\n\uD83D\uDD27 MICRO-TOOLS (${tools.length} crystallized)`);
  if (!tools.length) { console.log('  None yet.'); return; }
  tools.sort((a, b) => b.uses - a.uses).slice(0, 10).forEach(t =>
    console.log(`  ${t.name} (${t.uses}x)${t.autoGenerated ? ' [auto]' : ''}: ${t.trigger}`)
  );
}

function showRules() {
  const rules = load(path.join(HOME, 'evolve', 'workflow-rules.json'), []);
  console.log(`\n\uD83D\uDCCB RULES (${rules.length} active)`);
  if (!rules.length) { console.log('  None yet.'); return; }
  rules.forEach((r, i) =>
    console.log(`  ${i + 1}. [${r.priority}] WHEN "${r.when}" \u2192 ${r.then} (fired ${r.fired}x)`)
  );
}

console.log('═══ ZARA DASHBOARD ═══');
if (cmd === 'all' || cmd === 'memory') showMemory();
if (cmd === 'all' || cmd === 'metrics') showMetrics();
if (cmd === 'all' || cmd === 'patterns') showPatterns();
if (cmd === 'all' || cmd === 'procedures') showProcedures();
if (cmd === 'all' || cmd === 'tools') showMicroTools();
if (cmd === 'all' || cmd === 'rules') showRules();
console.log('');
